### ISSUE TITLE
Suspicious changeset in Colombia

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [OSMLatam/pow#3]
https://osmcha.org/changesets/126791464/

**Comment by risturiz** [comment]
User: https://www.openstreetmap.org/user/MarianaGG/ (Mapper since: September 07, 2022)

[#126791464](https://www.openstreetmap.org/changeset/126791464):

![changeset126791464-osmcha](https://user-images.githubusercontent.com/12375/193154920-4fe6170a-0b89-4469-a220-f6c70caa60d8.png)

- [ ] User alerted
- [ ] Error fixed
- [ ] Issue closed

**Comment by risturiz** [comment]
@set-reminder today 5pm Prueba

**Comment by risturiz** [comment]
Done https://www.openstreetmap.org/changeset/127546019

**Comment by erickdeoliveiraleal** [comment]
she deleted more highways: https://osmcha.org/changesets/126791579?filters=%7B%22users%22%3A%5B%7B%22label%22%3A%22MarianaGG%22%2C%22value%22%3A%22MarianaGG%22%7D%5D%2C%22date__gte%22%3A%5B%7B%22label%22%3A%22%22%2C%22value%22%3A%22%22%7D%5D%7D

**Comment by risturiz** [comment]
> she deleted more highways: https://osmcha.org/changesets/126791579?filters=%7B%22users%22%3A%5B%7B%22label%22%3A%22MarianaGG%22%2C%22value%22%3A%22MarianaGG%22%7D%5D%2C%22date__gte%22%3A%5B%7B%22label%22%3A%22%22%2C%22value%22%3A%22%22%7D%5D%7D

Pero este seria "otro" changeset :-)

**Comment by risturiz** [comment]
Creator: https://www.openstreetmap.org/user/MarianaGG/ (Mapper since: September 07, 2022)

[#126791579](https://www.openstreetmap.org/changeset/126791579):

![changeset126791579-osmcha](https://user-images.githubusercontent.com/12375/195967329-5b83fde4-4562-4128-b579-6bcc9b8f7ab7.png)

- [ ] User alerted
- [ ] Error fixed
- [ ] Issue closed

**Comment by risturiz** [comment]
Done https://www.openstreetmap.org/changeset/126791579
